### ISSUE TITLE
Mentor should be able to mark `assignment` as `completed`

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/galileo#89]
A `mentor` or a `facilitator` can mark for any exercise that the user has completed an assignment. The motivation of this is the offline interactions that happen between the mentor and the mentee. In the future release, some assignments can additionally have a parameter which disables `offline completion marking`.

**Comment by amarkrsinha1997** [comment]
@Rajat2008 Currently the completion process works like whenever the student has submitted an assignment of the course on which they are enrolled. The assignment is submitted to the student who has already completed that assignment or to the facilitator of that student center if no student have completed that assignment till yet.

So now what happens is every student has a mentor and the center where the student is has a facilitator.
So, the mentor and the facilitator keep tracks of there mentee progress and are the one who guides them.

So, the student has interaction with the mentor and the facilitator. So, we want that the facilitator or the mentor should also be available to mark the course completed for the student when he/ she shows it to there mentor or facilitator instead of waiting for the student who has been assigned the assignment to be reviewed, that saves the time of the student and also the mentor and the facilitator knows the progress of their mentee.

Note: Facilitator should be of the same center should be the priority if no facilitator is there assign it to other.

**Comment by koushik-nodejs** [comment]
@abhishekgupta92 @amarkrsinha1997 development and review completed , merging is pending

**Comment by amarkrsinha1997** [comment]
Reviewed and Closing
